ARG BASE_IMAGE
FROM $BASE_IMAGE

ENV DEBIAN_FRONTEND=noninteractive

# Change to working directory
WORKDIR /workspaces/sapience_nvidia_devel/

# RUN apt-get update
RUN sudo python -m pip install pexpect future
RUN rosdep install --from-paths src --ignore-src -y

# Install GeographicLib datasets:
RUN ./src/mavros/mavros/scripts/install_geographiclib_datasets.sh
