ARG BASE_IMAGE
FROM $BASE_IMAGE

ENV DEBIAN_FRONTEND=noninteractive
RUN sudo apt install -y python3-vcstool python3-rosinstall-generator

USER root
RUN wget https://raw.githubusercontent.com/mavlink/mavros/master/mavros/scripts/install_geographiclib_datasets.sh
RUN sudo chmod +x install_geographiclib_datasets.sh && ./install_geographiclib_datasets.sh
USER admin


